### ISSUE TITLE
Add `sans-serif` fallback font-family to the mithril.js.org website

### ISSUE THREAD

**Issue by d2s** [MithrilJS/mithril.js#2407]
### Description

Improve readability of the website by adding fallback font-family for the default font.

### Why

- Reduce the visual difference between unstyled content (before vs. after the webfont gets loaded).
- Allow page to work even when people have blocked Google Fonts from their browsers.
- Improve the page loading speed.

#### Currently:

```css
body, table, h5 {
    font: normal 16px 'Open Sans';
}
```

#### Consider changing that to:

```css
body, table, h5 {
    font-weight: normal;
    font-size: 16px;
    font-family: 'Open Sans', sans-serif;
}
```

### Is this something you're interested in working on?

Yes
