### ISSUE TITLE
No automatic redraw on animationend, undocumented

### ISSUE THREAD

**Issue by andypillip** [MithrilJS/mithril.js#2667]
The documentation mentions when automatic-redraw happens and when not:

> Mithril automatically redraws after DOM event handlers that are defined in a Mithril view:

> Mithril does not redraw after setTimeout, setInterval, requestAnimationFrame, raw Promise resolutions and 3rd party library event handlers […]

It does not happen on `animationend` either, which is a DOM event. Probably neither for `transitionend`.

Mithril 2.0.4

## Expected Behavior
– either Mithril should include the DOM event for auto-redraw
– or the documentation should mention that these events are not included

Thanks!

**Comment by isiahmeadows** [comment]
Do you have code reproducing the issue in question? Any deviation from the docs on automatic redraws is a bug in Mithril - that part is fairly complete.

**Comment by andypillip** [comment]
Sure thing:

```javascript
let runAnim = false; 

const onAnimEnd = () => {
    runAnim = false;
    m.redraw(); // Undocumented in Mithril documentation
};

const myComponent = {
    view: () => m("div", 
        { 
            onclick:  () => {runAnim = true}, 
            className: runAnim ? "myAnim" : "",
            oncreate: (vnode) => vnode.dom.addEventListener("animationend", onAnimEnd)            
        }, 
        "Hello world"
    )
};

m.mount(document.body, myComponent);
```

```css
.myAnim {
  animation: fade-back-out;
}
.myAnim {animation:fade-out-in 3s;}

@keyframes fade-out-in {
    0% {background: #FFFFFF;}
    50% {background: #94FF57;}
    100% {background:#FFFFFF;}
}
```
